### ISSUE TITLE
مشکل قالب

### ISSUE THREAD

**Issue by motorola30** [mybbiran/Persian-MyBB-1.8.X#16]
سلام

مشکلی در راست و چپ قالب مشاهده شد
تصویر پیوست شد
البته با لوکال هاست تست و مشاهده شد

![189](https://cloud.githubusercontent.com/assets/10397427/21265837/84760e7e-c3b8-11e6-954d-13375be75ded.jpg)

**Comment by motorola30** [comment]
مشکل اول برطرف شد
تغییر راست به چپ کد زیر
لاین : 9653
`<template name="postbit_posturl" version="1801"><![CDATA[<div class="float_left" style="vertical-align: top">`
کد جدید : float_left
کد قدیمی : float_right
---------------------------------------------------------
**همچنان مشکل راست به چپ کد باقیست**

**Comment by firstboy000** [comment]
.codeblock code
به کلاس فوق خاصیت های زیر افزوده شد.
direction: ltr;
text-align: left;
راست چین بودن کد ها رفع گردید.
مشکلات رفع گردید، issue بسته شد×
