### ISSUE TITLE
نیاز به برسی فایل زبان

### ISSUE THREAD

**Issue by motorola30** [mybbiran/Persian-MyBB-1.8.X#8]
لطفا دوستان هم برسی کنن

https://github.com/mybbiran/Persian-Language-For-MyBB-1.8.X/commit/f67dabf09d1f9e4cf64769702ad2d17a01dc5c8f#diff-f344db74f4cab15c41f8164fdabecae1

**Comment by firstboy000** [comment]
لینک چک شد، خوبه. مثل پک اصلی شد.

فقط مسئله اینجاست که حجم زیادیه و زمان بر. بهتره که کل فایل ها بررسی نشن و مابقی افزوده های سایت مادر اضافه و پوش میشن. ماقبل اگر قسمتی رو دیدم که ترجمه نشده یا بد ترجمه شده رو به عنوان issue گزارش کنیم تا رفع بشه. اینطور به نظرم بهتره

**Comment by motorola30** [comment]
سلام

پس مشکلات  که مشاهده میشه رو حل میکنیم و  نسخه 1.8.9 که اومد به همین نسخه اصلاح شده اضافه میکنیم
