### ISSUE TITLE
helpdocs.lang بازنگری فایل 

### ISSUE THREAD

**Issue by motorola30** [mybbiran/Persian-MyBB-1.8.X#9]
helpdocs.lang بازنگری فایل 

با فایل اصلی تغییرات زیادی دارد helpdocs.lang فایل

**Comment by firstboy000** [comment]
آیا موارد افزوده شده ای در بسته زبان انگلیسی 1.8.8هست که در پارسی شده اضافه نشده؟
یا اینکه برای نسخه 1.8.9 تغییرات داشته؟

**Comment by motorola30** [comment]
چک شد  ExamDiff Pro 8.0 بله ، تویه نسخه انگلیسی با فارسی با برنامه
تغییرات داره که بهتر میدونم با برنامه بالا مقایسه بشه و تغییرات اعمال بشه
البته نسخه های قدیمی چک نکردم 
این مورد برای 1.8.9 باید اصلاح بشه

**Comment by firstboy000** [comment]
بررسی شد، مشکلی نداشت و کمبودی از نسخه 1.8 تا نسخه فعلی موجود در مخزنمون نداشت
تنها از نسخه 1.6 به بعد یه سری افعال به حالت گذشته درآمدند که تاثیری در متن نداشتند.
